# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: 전북대 이혜원
# Website URL
baseURL: 'https://ehyewon.github.io/'

############################
## LANGUAGE
############################

defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: true
removePathAccents: true

languages:
  ko:
    languageCode: ko-kr
    languageName: 한국어
    weight: 1
    contentDir: content/ko
    title: 전북대 | 이혜원

  en:
    languageCode: en-us
    languageName: English
    weight: 2
    contentDir: content/en
    title: JBNU | LeeHyeWon



############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true
outputs:
  home: [HTML, RSS, JSON]        # ✅ JSON 추가 (중요)
  section: [HTML, RSS, JSON]
  taxonomy: [HTML, RSS, JSON]
  term: [HTML, RSS, JSON]
  page: [HTML, RSS, JSON]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
params:
  custom_css:
    - css/custom.css